# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd10284492846b95b4b131236effb0312a703c0e3be5ad97094e11db80ca4e3edaa53471f24d6299e63c17c6bd743a6d801a9c133e0320c8bd8f3894ccd1816

test:
  secret_key_base: 8a045488a9be9149ff71dbc252af8eb77fe88ddf28d1f87dcb0ad119524feeac81cc35342941c0ec46cd5e2eac1468f06bf0b376d827591e75713c3910729111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
